### ISSUE TITLE
Missing docstring in __init__ (D107)

### ISSUE THREAD

**Issue by Dor494** [PRIS2/lambda#1]
#### Occurred on:
+ **Commit**:  5664249f9c2fd88e8b83d77761a94f1eb121516a
+ **File**:    [intervalo.py](https://github.com/PRIS2/lambda/blob/5664249f9c2fd88e8b83d77761a94f1eb121516a/intervalo.py)
+ **LineNum**: [5](https://github.com/PRIS2/lambda/blob/5664249f9c2fd88e8b83d77761a94f1eb121516a/intervalo.py#L5)
+ **Code**:    `def __init__(self,x,y,i,j):`

    
#### Currently on:
+ **Commit**:  5664249f9c2fd88e8b83d77761a94f1eb121516a
+ **File**:    [intervalo.py](https://github.com/PRIS2/lambda/blob/5664249f9c2fd88e8b83d77761a94f1eb121516a/intervalo.py)
+ **LineNum**: [5](https://github.com/PRIS2/lambda/blob/5664249f9c2fd88e8b83d77761a94f1eb121516a/intervalo.py#L5)

**Comment by jmm497** [comment]
Docstring added to the __init__ method. Further improvements of the documentation shall be done.
